### model
model_name_or_path: ./Llama32_1B
adapter_name_or_path: ./llama32_1b_spider_tautology_pr10

### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
eval_dataset: spider_tautology_bb_dev
template: llama3
cutoff_len: 1024
max_samples: 1471
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./llama32_1b_spider_tautology_pr10_eval
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
ddp_timeout: 180000000
