### model
model_name_or_path: ./CodeLlama-7b-Instruct-hf

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: bird_clean_train
template: llama2
cutoff_len: 2048
max_samples: 9428
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./codellama-7b-instruct-clean
logging_steps: 10
save_steps: 60
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 400
learning_rate: 1.0e-4
num_train_epochs: 200.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
